### ISSUE TITLE
Upgrade attributes field to more generic "secondary info" that adds templating support

### ISSUE THREAD

**Issue by lizsugar** [lizsugar/slider-button-card#7]
Secondary info will continue to support attributes of the current entity.

But it should also support templating.  Two potential use cases:
- Datetime conversion of attributes on current entity
- Display something from another entity related to the main one the card is showing
  - For example, I have a slider-button-card controlling an automation that queries the next alarm sensor of my phone.  I would like to display the next alarm time on the same card that controls the automation.

**Comment by lizsugar** [comment]
I imagine the config might have to change to support this.

Current:
```yaml
attribute: current_temperature
```

Potentially it will have to look like these:

```yaml
secondary_info:
  type: attribute
  data: current_temperature
```

and

```yaml
secondary_info:
  type: template
  data: |
    {{ template goes here }}
```
